name:                warp-grpc
version:             0.1.0.3
github:              "lucasdicioccio/warp-grpc"
license:             BSD3
author:              "Lucas DiCioccio"
maintainer:          "lucas@dicioccio.fr"
copyright:           "2017 Lucas DiCioccio"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            A minimal gRPC server on top of Warp.
category:            Networking

description:         Please see the README on Github at <https://github.com/lucasdicioccio/warp-grpc#readme>

dependencies:
- base >= 4.7 && < 5
- async
- binary
- bytestring
- case-insensitive
- http2-grpc-types >= 0.2
- http-types
- proto-lens
- wai
- warp >= 3.2.24 && < 3.3
- warp-tls

library:
  source-dirs: src
