resolver: lts-11.12
packages:
- .
- ../http2-client-grpc
- location:
    git: https://github.com/lucasdicioccio/wai.git
    commit: 58742ddbcba48b6bf9a141b38ac0cece23e02163
  subdirs:
  - wai
  - wai-http2-extra
  - warp
  - warp-tls
  extra-dep: true
extra-deps:
- http2-client-0.8.0.0
- lens-labels-0.2.0.1
- proto-lens-0.3.1.0
- proto-lens-combinators-0.1.0.10
- proto-lens-protobuf-types-0.3.0.1
- proto-lens-protoc-0.3.1.0
  #- http2-client-grpc-0.1.0.1
flags: {}
extra-package-dbs: []
